# Arrays

In [36]:
#creating an array using module
import array

In [37]:
arr = array.array("i",[23,1,21,67,27,34,11])
print(arr)
print(type(arr))

array('i', [23, 1, 21, 67, 27, 34, 11])
<class 'array.array'>


In [38]:
#access a single value -> index
print(arr[0])

23


In [39]:
#slicing method
print(arr[1:5])

array('i', [1, 21, 67, 27])


In [40]:
#iterate -> for loop
for i in arr:
    print(i)

23
1
21
67
27
34
11


In [41]:
#append()
print("original Array:",arr)
arr.append(100)
print("After adding:",arr)

original Array: array('i', [23, 1, 21, 67, 27, 34, 11])
After adding: array('i', [23, 1, 21, 67, 27, 34, 11, 100])


In [42]:
#insert()
print("original Array:",arr)
arr.insert(3,14)
print("After adding:",arr)

original Array: array('i', [23, 1, 21, 67, 27, 34, 11, 100])
After adding: array('i', [23, 1, 21, 14, 67, 27, 34, 11, 100])


In [43]:
#extend()
print("original Array:",arr)
arr.extend([10,89,56])
print("After adding:",arr)

original Array: array('i', [23, 1, 21, 14, 67, 27, 34, 11, 100])
After adding: array('i', [23, 1, 21, 14, 67, 27, 34, 11, 100, 10, 89, 56])


In [44]:
#len()
print(len(arr))

12


In [45]:
#count()
print(arr.count(100))

1


In [46]:
#index()
print(arr.index(27))

5


In [47]:
print("original Array:",arr)
#min()
print(min(arr))
#max()
print(max(arr))
#sum()
print(sum(arr))

original Array: array('i', [23, 1, 21, 14, 67, 27, 34, 11, 100, 10, 89, 56])
1
100
453


In [48]:
#pop()
print("original Array:",arr)
print(arr.pop())
print("After Deleting:",arr)

original Array: array('i', [23, 1, 21, 14, 67, 27, 34, 11, 100, 10, 89, 56])
56
After Deleting: array('i', [23, 1, 21, 14, 67, 27, 34, 11, 100, 10, 89])


In [49]:
#pop(index)
print("original Array:",arr)
print(arr.pop(3))
print("After Deleting:",arr)

original Array: array('i', [23, 1, 21, 14, 67, 27, 34, 11, 100, 10, 89])
14
After Deleting: array('i', [23, 1, 21, 67, 27, 34, 11, 100, 10, 89])


In [50]:
#remove(value)
print("original Array:",arr)
arr.remove(100)
print("After Deleting:",arr)

original Array: array('i', [23, 1, 21, 67, 27, 34, 11, 100, 10, 89])
After Deleting: array('i', [23, 1, 21, 67, 27, 34, 11, 10, 89])


In [51]:
#del v_n[index]

print("original Array:",arr)
del arr[2]
print("After Deleting:",arr)

original Array: array('i', [23, 1, 21, 67, 27, 34, 11, 10, 89])
After Deleting: array('i', [23, 1, 67, 27, 34, 11, 10, 89])


In [52]:
#sort()

print("original Array:",arr)
l = list(arr)
l.sort()
arr = array.array('i',l)
print("After sorting:",arr)

original Array: array('i', [23, 1, 67, 27, 34, 11, 10, 89])
After sorting: array('i', [1, 10, 11, 23, 27, 34, 67, 89])


In [1]:
#creating an array using library(NUMPY)
import numpy

In [2]:
sample = numpy.array([12,45,67,22,67,78,34,90])
print(sample)
print(type(sample))

[12 45 67 22 67 78 34 90]
<class 'numpy.ndarray'>


In [3]:
#replacement

print("Original Array;",sample)
sample[2] = 70
print("After replacing ,Array be:",sample)

Original Array; [12 45 67 22 67 78 34 90]
After replacing ,Array be: [12 45 70 22 67 78 34 90]


In [4]:
#access a single value -> index
print(sample[6])

34


In [5]:
#slicing method
print(sample[1:6])

[45 70 22 67 78]


In [6]:
#len()
print(len(sample))

8


In [7]:
#append() -> numpy.append(v_n,new_value)
print("Original Array:",sample)
na = numpy.append(sample,23)
print("New_array:",na)
print("After adding ,Array be:",sample)

Original Array; [12 45 70 22 67 78 34 90]
New_array: [12 45 70 22 67 78 34 90 23]
After adding ,Array be: [12 45 70 22 67 78 34 90]


In [9]:
#insert() -> numpy.insert(v_n,pos,new_value)
print("Original Array;",sample)
na = numpy.insert(sample,1,100)
print("New_array:",na)
print("After adding ,Array be:",sample)

Original Array; [12 45 70 22 67 78 34 90]
New_array: [ 12 100  45  70  22  67  78  34  90]
After adding ,Array be: [12 45 70 22 67 78 34 90]


In [10]:
#delete() -> particular value
print("Original Array:",sample)
na = numpy.delete(sample,3)
print("New_array:",na)
print("After deleting ,Array be:",sample)

Original Array: [12 45 70 22 67 78 34 90]
New_array: [12 45 70 67 78 34 90]
After deleting ,Array be: [12 45 70 22 67 78 34 90]


In [11]:
#where(v_n==value) -> used to get the position of a particular value
print("Original Array:",sample)
print(numpy.where(sample==78))

Original Array: [12 45 70 22 67 78 34 90]
(array([5], dtype=int64),)


In [16]:
#sort(v_n) -> ascending order
print("Original Array:",sample)
na = numpy.sort(sample)
print("New_array in Ascending Order:",na)
print("After sorting ,Array be:",sample)

Original Array: [12 45 70 22 67 78 34 90]
New_array in Ascending Order: [12 22 34 45 67 70 78 90]
After sorting ,Array be: [12 45 70 22 67 78 34 90]


In [17]:
#sort(v_n)[::-1] -> descending order
print("Original Array:",sample)
na = numpy.sort(sample)[::-1]
print("New_array in Descending Order:",na)
print("After sorting ,Array be:",sample)

Original Array: [12 45 70 22 67 78 34 90]
New_array in Descending Order: [90 78 70 67 45 34 22 12]
After sorting ,Array be: [12 45 70 22 67 78 34 90]


# Arithmetic Operation on Arrays

In [26]:
a1 = numpy.array([1,2,3,4])
a2 = numpy.array([10,20,30,40])
#addition
print("Addition:",a1+a2)
#subtraction
print("Subraction:",a2-a1)
#Multiplication
print("Multiplication:",a2*a1)
#division
print("division:",a2%a1)
#power
print("power:",a1**2)

Addition: [11 22 33 44]
Subraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
division: [0 0 0 0]
power: [ 1  4  9 16]
